version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn music_one.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/music_one/web/static
#      - media_volume:/home/music_one/web/media
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/music_one/web/static
#      - media_volume:/home/music_one/web/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: