# Generated by Django 2.2.16 on 2020-10-04 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insta_parser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='igtv',
            name='hash_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igtvs', to='insta_parser.IgtvHashtag'),
        ),
        migrations.AddField(
            model_name='igtv',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='igtvs', to=settings.AUTH_USER_MODEL),
        ),
    ]
